# Forward DNS requests from remote WireGuard clients to the default
# gateway on the internal bridged network that the WireGuard container
# is attached to. This results in queries being sent to any other
# container on the same internal bridged network that is listening
# on port 53 (eg PiHole, AdGuardHome or bind9).
#
# Acknowledgement: @ukkopahis

GW=$(ip route list default | head -1 | cut -d " " -f 3)
echo Creating Corefile to use DNS at $GW
echo "# Generated by use-container-dns.sh
. {
    loop
    forward . dns://${GW}
}" > /config/coredns/Corefile

