  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 9080:8080
    environment:
      - VIRTUAL_HOST=~^adminer\..*\.xip\.io
      - VIRTUAL_PORT=9080
